// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config/config.proto

package config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type App struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId                string   `protobuf:"bytes,2,opt,name=appId,proto3" json:"appId,omitempty"`
	AppName              string   `protobuf:"bytes,3,opt,name=appName,proto3" json:"appName,omitempty"`
	CreatedTime          int64    `protobuf:"varint,4,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	UpdatedTime          int64    `protobuf:"varint,5,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}
func (*App) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{0}
}

func (m *App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_App.Unmarshal(m, b)
}
func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_App.Marshal(b, m, deterministic)
}
func (m *App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App.Merge(m, src)
}
func (m *App) XXX_Size() int {
	return xxx_messageInfo_App.Size(m)
}
func (m *App) XXX_DiscardUnknown() {
	xxx_messageInfo_App.DiscardUnknown(m)
}

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *App) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *App) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *App) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *App) GetUpdatedTime() int64 {
	if m != nil {
		return m.UpdatedTime
	}
	return 0
}

type Cluster struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AppId                string   `protobuf:"bytes,3,opt,name=appId,proto3" json:"appId,omitempty"`
	CreatedTime          int64    `protobuf:"varint,4,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	UpdatedTime          int64    `protobuf:"varint,5,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cluster) Reset()         { *m = Cluster{} }
func (m *Cluster) String() string { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()    {}
func (*Cluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{1}
}

func (m *Cluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster.Unmarshal(m, b)
}
func (m *Cluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster.Marshal(b, m, deterministic)
}
func (m *Cluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster.Merge(m, src)
}
func (m *Cluster) XXX_Size() int {
	return xxx_messageInfo_Cluster.Size(m)
}
func (m *Cluster) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster proto.InternalMessageInfo

func (m *Cluster) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Cluster) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cluster) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *Cluster) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *Cluster) GetUpdatedTime() int64 {
	if m != nil {
		return m.UpdatedTime
	}
	return 0
}

type Env struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AppId                string   `protobuf:"bytes,3,opt,name=appId,proto3" json:"appId,omitempty"`
	CreatedTime          int64    `protobuf:"varint,4,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	UpdatedTime          int64    `protobuf:"varint,5,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Env) Reset()         { *m = Env{} }
func (m *Env) String() string { return proto.CompactTextString(m) }
func (*Env) ProtoMessage()    {}
func (*Env) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{2}
}

func (m *Env) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Env.Unmarshal(m, b)
}
func (m *Env) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Env.Marshal(b, m, deterministic)
}
func (m *Env) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Env.Merge(m, src)
}
func (m *Env) XXX_Size() int {
	return xxx_messageInfo_Env.Size(m)
}
func (m *Env) XXX_DiscardUnknown() {
	xxx_messageInfo_Env.DiscardUnknown(m)
}

var xxx_messageInfo_Env proto.InternalMessageInfo

func (m *Env) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Env) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Env) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *Env) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *Env) GetUpdatedTime() int64 {
	if m != nil {
		return m.UpdatedTime
	}
	return 0
}

type Instance struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId                string   `protobuf:"bytes,2,opt,name=appId,proto3" json:"appId,omitempty"`
	ClusterName          string   `protobuf:"bytes,3,opt,name=clusterName,proto3" json:"clusterName,omitempty"`
	Ip                   string   `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	CreatedTime          int64    `protobuf:"varint,5,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	UpdatedTime          int64    `protobuf:"varint,6,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Instance) Reset()         { *m = Instance{} }
func (m *Instance) String() string { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()    {}
func (*Instance) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{3}
}

func (m *Instance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instance.Unmarshal(m, b)
}
func (m *Instance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instance.Marshal(b, m, deterministic)
}
func (m *Instance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instance.Merge(m, src)
}
func (m *Instance) XXX_Size() int {
	return xxx_messageInfo_Instance.Size(m)
}
func (m *Instance) XXX_DiscardUnknown() {
	xxx_messageInfo_Instance.DiscardUnknown(m)
}

var xxx_messageInfo_Instance proto.InternalMessageInfo

func (m *Instance) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Instance) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *Instance) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *Instance) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Instance) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *Instance) GetUpdatedTime() int64 {
	if m != nil {
		return m.UpdatedTime
	}
	return 0
}

type Item struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NamespaceId          int64    `protobuf:"varint,2,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Comment              string   `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	LineNo               int32    `protobuf:"varint,6,opt,name=lineNo,proto3" json:"lineNo,omitempty"`
	CreatedTime          int64    `protobuf:"varint,7,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	UpdatedTime          int64    `protobuf:"varint,8,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{4}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Item) GetNamespaceId() int64 {
	if m != nil {
		return m.NamespaceId
	}
	return 0
}

func (m *Item) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Item) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Item) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *Item) GetLineNo() int32 {
	if m != nil {
		return m.LineNo
	}
	return 0
}

func (m *Item) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *Item) GetUpdatedTime() int64 {
	if m != nil {
		return m.UpdatedTime
	}
	return 0
}

type Namespace struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId                string   `protobuf:"bytes,2,opt,name=appId,proto3" json:"appId,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ClusterName          string   `protobuf:"bytes,4,opt,name=clusterName,proto3" json:"clusterName,omitempty"`
	CreatedTime          int64    `protobuf:"varint,5,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	UpdatedTime          int64    `protobuf:"varint,6,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Namespace) Reset()         { *m = Namespace{} }
func (m *Namespace) String() string { return proto.CompactTextString(m) }
func (*Namespace) ProtoMessage()    {}
func (*Namespace) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{5}
}

func (m *Namespace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Namespace.Unmarshal(m, b)
}
func (m *Namespace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Namespace.Marshal(b, m, deterministic)
}
func (m *Namespace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Namespace.Merge(m, src)
}
func (m *Namespace) XXX_Size() int {
	return xxx_messageInfo_Namespace.Size(m)
}
func (m *Namespace) XXX_DiscardUnknown() {
	xxx_messageInfo_Namespace.DiscardUnknown(m)
}

var xxx_messageInfo_Namespace proto.InternalMessageInfo

func (m *Namespace) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Namespace) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *Namespace) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Namespace) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *Namespace) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *Namespace) GetUpdatedTime() int64 {
	if m != nil {
		return m.UpdatedTime
	}
	return 0
}

type ConfigRequest struct {
	App                  *App     `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigRequest) Reset()         { *m = ConfigRequest{} }
func (m *ConfigRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigRequest) ProtoMessage()    {}
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{6}
}

func (m *ConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigRequest.Unmarshal(m, b)
}
func (m *ConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigRequest.Marshal(b, m, deterministic)
}
func (m *ConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigRequest.Merge(m, src)
}
func (m *ConfigRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigRequest.Size(m)
}
func (m *ConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigRequest proto.InternalMessageInfo

func (m *ConfigRequest) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{7}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ConfigResponse struct {
	Error                *Error     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	App                  *App       `protobuf:"bytes,3,opt,name=app,proto3" json:"app,omitempty"`
	AppList              []*App     `protobuf:"bytes,4,rep,name=appList,proto3" json:"appList,omitempty"`
	Cluster              *Cluster   `protobuf:"bytes,5,opt,name=cluster,proto3" json:"cluster,omitempty"`
	ClusterList          []*Cluster `protobuf:"bytes,6,rep,name=clusterList,proto3" json:"clusterList,omitempty"`
	Env                  *Env       `protobuf:"bytes,7,opt,name=env,proto3" json:"env,omitempty"`
	EnvList              []*Env     `protobuf:"bytes,8,rep,name=envList,proto3" json:"envList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ConfigResponse) Reset()         { *m = ConfigResponse{} }
func (m *ConfigResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigResponse) ProtoMessage()    {}
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{8}
}

func (m *ConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigResponse.Unmarshal(m, b)
}
func (m *ConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigResponse.Marshal(b, m, deterministic)
}
func (m *ConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigResponse.Merge(m, src)
}
func (m *ConfigResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigResponse.Size(m)
}
func (m *ConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigResponse proto.InternalMessageInfo

func (m *ConfigResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ConfigResponse) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

func (m *ConfigResponse) GetAppList() []*App {
	if m != nil {
		return m.AppList
	}
	return nil
}

func (m *ConfigResponse) GetCluster() *Cluster {
	if m != nil {
		return m.Cluster
	}
	return nil
}

func (m *ConfigResponse) GetClusterList() []*Cluster {
	if m != nil {
		return m.ClusterList
	}
	return nil
}

func (m *ConfigResponse) GetEnv() *Env {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *ConfigResponse) GetEnvList() []*Env {
	if m != nil {
		return m.EnvList
	}
	return nil
}

func init() {
	proto.RegisterType((*App)(nil), "App")
	proto.RegisterType((*Cluster)(nil), "Cluster")
	proto.RegisterType((*Env)(nil), "Env")
	proto.RegisterType((*Instance)(nil), "Instance")
	proto.RegisterType((*Item)(nil), "Item")
	proto.RegisterType((*Namespace)(nil), "Namespace")
	proto.RegisterType((*ConfigRequest)(nil), "ConfigRequest")
	proto.RegisterType((*Error)(nil), "Error")
	proto.RegisterType((*ConfigResponse)(nil), "ConfigResponse")
}

func init() { proto.RegisterFile("config/config.proto", fileDescriptor_cc332a44e926b360) }

var fileDescriptor_cc332a44e926b360 = []byte{
	// 607 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x95, 0x5f, 0x8e, 0xd3, 0x3e,
	0x10, 0xc7, 0x7f, 0x69, 0xfe, 0xb4, 0x9d, 0xfc, 0x76, 0x17, 0x19, 0x84, 0x22, 0x84, 0x50, 0x95,
	0x17, 0x56, 0xa0, 0xcd, 0x42, 0x97, 0x0b, 0x54, 0xa5, 0x5a, 0x55, 0x42, 0x7d, 0xb0, 0xe0, 0x00,
	0x21, 0x19, 0x56, 0x11, 0x8d, 0x63, 0x92, 0x34, 0x12, 0xcf, 0x3c, 0x20, 0x2e, 0xc2, 0x0b, 0x07,
	0xe0, 0x26, 0x1c, 0x83, 0x33, 0x20, 0x8f, 0x93, 0x36, 0xdb, 0x3e, 0xd4, 0x48, 0x2b, 0xf1, 0x54,
	0x7b, 0x3c, 0x33, 0xfe, 0xcc, 0x77, 0xe2, 0x29, 0xdc, 0x4f, 0x0a, 0xf1, 0x21, 0xbb, 0xb9, 0xd4,
	0x3f, 0x91, 0x2c, 0x8b, 0xba, 0x08, 0xbf, 0x59, 0x60, 0xcf, 0xa4, 0x64, 0xa7, 0x30, 0xc8, 0xd2,
	0xc0, 0x9a, 0x58, 0xe7, 0x36, 0x1f, 0x64, 0x29, 0x7b, 0x00, 0x6e, 0x2c, 0xe5, 0x32, 0x0d, 0x06,
	0x13, 0xeb, 0x7c, 0xcc, 0xf5, 0x86, 0x05, 0x30, 0x8c, 0xa5, 0x5c, 0xc5, 0x39, 0x06, 0x36, 0xd9,
	0xbb, 0x2d, 0x9b, 0x80, 0x9f, 0x94, 0x18, 0xd7, 0x98, 0xbe, 0xcd, 0x72, 0x0c, 0x1c, 0x4a, 0xd4,
	0x37, 0x29, 0x8f, 0x8d, 0x4c, 0xb7, 0x1e, 0xae, 0xf6, 0xe8, 0x99, 0xc2, 0xaf, 0x16, 0x0c, 0xe7,
	0xeb, 0x4d, 0x55, 0x63, 0x79, 0xc0, 0xc3, 0xc0, 0x11, 0xea, 0x5a, 0x8d, 0x43, 0xeb, 0x1d, 0xa3,
	0xdd, 0x67, 0xbc, 0x0b, 0x92, 0x2f, 0x16, 0xd8, 0x0b, 0xd1, 0xfc, 0x63, 0x8a, 0xef, 0x16, 0x8c,
	0x96, 0xa2, 0xaa, 0x63, 0x91, 0xa0, 0x61, 0x83, 0xd4, 0xb5, 0x5a, 0xc1, 0x5e, 0x93, 0xfa, 0x26,
	0xca, 0x23, 0x89, 0x67, 0xcc, 0x07, 0x99, 0xdc, 0x07, 0x75, 0x8f, 0x82, 0x7a, 0x87, 0xa0, 0xbf,
	0x2c, 0x70, 0x96, 0x35, 0xe6, 0x07, 0x90, 0x13, 0xf0, 0x95, 0x46, 0x95, 0x8c, 0x13, 0x6c, 0x51,
	0x6d, 0xde, 0x37, 0xb1, 0x7b, 0x60, 0x7f, 0xc4, 0xcf, 0x2d, 0xa8, 0x5a, 0xaa, 0xc2, 0x9a, 0x78,
	0xbd, 0xc1, 0x96, 0x51, 0x6f, 0xd4, 0x97, 0x97, 0x14, 0x79, 0x8e, 0xa2, 0x26, 0xc4, 0x31, 0xef,
	0xb6, 0xec, 0x21, 0x78, 0xeb, 0x4c, 0xe0, 0xaa, 0x20, 0x32, 0x97, 0xb7, 0xbb, 0xfd, 0xc2, 0x86,
	0x47, 0x0b, 0x1b, 0x1d, 0x16, 0xf6, 0xc3, 0x82, 0xf1, 0xaa, 0xa3, 0x35, 0x6c, 0x41, 0xf7, 0x8d,
	0xd8, 0xbd, 0x6f, 0x64, 0xaf, 0x2d, 0xce, 0x61, 0x5b, 0xee, 0xa2, 0x0d, 0x4f, 0xe1, 0x64, 0x4e,
	0x6f, 0x9b, 0xe3, 0xa7, 0x0d, 0x56, 0x4a, 0x1a, 0x3b, 0x96, 0x92, 0x88, 0xfd, 0xa9, 0x13, 0xcd,
	0xa4, 0xe4, 0xca, 0x10, 0x5e, 0x80, 0xbb, 0x28, 0xcb, 0xa2, 0x54, 0xac, 0x49, 0x91, 0x22, 0x79,
	0xb8, 0x9c, 0xd6, 0xaa, 0x23, 0x79, 0x75, 0xd3, 0xd6, 0xa4, 0x96, 0xe1, 0x6f, 0x0b, 0x4e, 0xbb,
	0xc4, 0x95, 0x2c, 0x44, 0x85, 0xec, 0x31, 0xb8, 0xa8, 0x32, 0x90, 0x9b, 0x3f, 0xf5, 0x22, 0xca,
	0xc7, 0xb5, 0xb1, 0xbb, 0xd7, 0xde, 0xbb, 0x97, 0x3d, 0xa1, 0xf1, 0xf1, 0x26, 0xab, 0xea, 0xc0,
	0x99, 0xd8, 0xdb, 0xb3, 0xce, 0xc8, 0x42, 0x18, 0xb6, 0x9a, 0x90, 0x00, 0xfe, 0x74, 0x14, 0xb5,
	0xf3, 0x80, 0x77, 0x07, 0xec, 0xd9, 0x56, 0x4a, 0xca, 0xe3, 0x51, 0x9e, 0x9d, 0x5f, 0xff, 0x50,
	0x71, 0xa0, 0x68, 0xa8, 0xf5, 0xea, 0xae, 0x85, 0x68, 0xb8, 0x32, 0x28, 0x0e, 0x14, 0x0d, 0xc5,
	0x8f, 0x5a, 0x0e, 0x75, 0xd6, 0x19, 0xa7, 0x3f, 0x5d, 0xf0, 0x74, 0xc1, 0x2c, 0x82, 0xf1, 0x9c,
	0x9a, 0x40, 0x43, 0x32, 0xba, 0xa5, 0xef, 0xa3, 0xb3, 0xe8, 0xb6, 0x2c, 0xe1, 0x7f, 0xec, 0x02,
	0x46, 0x2a, 0xc5, 0x4c, 0xca, 0xca, 0xc4, 0xfd, 0x39, 0x78, 0xd7, 0x58, 0x1b, 0xe6, 0x9e, 0xc2,
	0x89, 0x66, 0xd9, 0x0e, 0xc9, 0xe3, 0x31, 0x97, 0x00, 0xd7, 0x58, 0xff, 0x45, 0xc0, 0x4b, 0xf8,
	0x5f, 0x15, 0xd0, 0x46, 0x18, 0x15, 0xb1, 0xd5, 0x88, 0x46, 0xa6, 0x69, 0xd1, 0x86, 0xce, 0xad,
	0xa0, 0x0b, 0xd1, 0x18, 0xb1, 0x5c, 0xc1, 0xa9, 0x66, 0xd9, 0x0d, 0xce, 0xe3, 0x41, 0xaf, 0xe0,
	0x4c, 0x07, 0xf5, 0xde, 0xba, 0x91, 0xb4, 0xed, 0x55, 0x34, 0xfa, 0x8c, 0x02, 0xde, 0xd1, 0x73,
	0x35, 0x0d, 0x78, 0x01, 0xfe, 0x6b, 0x5c, 0xa3, 0x0e, 0x30, 0x29, 0xff, 0xbd, 0x47, 0xff, 0xea,
	0x57, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4f, 0xdc, 0xc8, 0xee, 0xec, 0x07, 0x00, 0x00,
}
