micro:
  config_server:
    db:
      dialect: mysql
      orm: gorm
      gorm:
        logMode: true
        autoMigrate: true
      mysql:
        url: root:123456@(172.17.162.214:3306)/just_for_test_dont_delete_plz?charset=utf8&parseTime=true&loc=Asia%2FShanghai
        maxIdleConnection: 100
        maxOpenConnection: 130
