micro:
  config_server:
    db:
      dialect: mysql
      mysql:
        url: root:123@(127.0.0.1:3306)/config-server?charset=utf8&parseTime=true&loc=Asia%2FShanghai
        maxIdleConnection: 100
        maxOpenConnection: 130
